### ISSUE TITLE
TypeError with import_from_itunes.py

### ISSUE THREAD

**Issue by VenomQuartz** [Tamriel/quod_libet_import_itunes_ratings#1]
During the step where I use import_from_itunes.py, I get this: 

> Traceback (most recent call last):
>   File "import_from_itunes.py", line 10, in <module>
>     key = song.artist + song.album + song.name
> TypeError: Can't convert 'NoneType' object to str implicitly
> Username:quod_libet_import_itunes_ratings-master Username$

**Comment by Tamriel** [comment]
Oh. I guess one of your songs has no artist, album or name tagged.
Is it possible for you to fix that?

**Comment by VenomQuartz** [comment]
Ahh. Yeah, that would easy to fix. I'll see to that and report back.

**Comment by VenomQuartz** [comment]
Alright, I got around to fixing it, and the problem's gone. However, I've got _another_ issue that I can't figure out. I'll open a new issue for that.
